title: ğŸ—£ï¸ Samtale
description: Empowering organizations and authorities to collaborate effectively
  through focused discussions.
url: https://os2sandbox.github.io/sandbox-samtale-documentation/
cover: /assets/media/16-sunrise-on-water-1.png
