title: üó£Ô∏è Samtale
description: Empowering organizations and authorities to collaborate effectively through focused discussions.
theme: just-the-docs

# Base URL for GitHub Pages
url: https://os2sandbox.github.io/sandbox-samtale-documentation/

# Auxiliary links
aux_links:
  Samtale is using Zulip: https://zulip.readthedocs.io/en/latest/
  Issue tracker p√• Github: https://github.com/OS2sandbox/sandbox-samtale

# Makes auxiliary links open in a new tab
aux_links_new_tab: true

# Enable or disable the side/mobile menu globally
nav_enabled: true

# Sort order for navigation links
nav_sort: case_sensitive # Capital letters sorted before lowercase

# Show navigation error report
nav_error_report: true

# Include the "docs" folder in the build
include:
  - docs

# Enable the Just the Docs navigation
just_the_docs:
  collections:
    docs:
      output: true # Ensures the "docs" collection is rendered
  navigation:
    structure: nested # Enables nested navigation for subfolders

# Default settings for files in the "docs" folder
defaults:
  - scope:
      path: "docs" # Targets the "docs" folder
      type: "pages"
    values:
      layout: "default" # Use the default layout provided by the theme
      nav_exclude: false # Include in navigation
